sudo: required
dist: trusty
language: node_js
node_js:
  - node

services:
  - postgresql

before_script:
  - npm install
  - psql -c 'create database docMan-test;' -U postgres
  - dropdb --if-exists docMan-test && createdb docMan-test
  - sequelize db:migrate --env test


after_success:
  - npm run coverage
  - npm run coveralls

after_failure:
  - npm run coverage
  - npm run coveralls
